//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Metro.Model
{
    using E_Metro.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class RailWay : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RailWay()
        {
            this.MonthlyTickets = new HashSet<MonthlyTicket>();
            this.StandarTickets = new HashSet<StandarTicket>();
            this.TicketSolds = new HashSet<TicketSold>();
        }
    
        public int Id { get; set; }
        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private Nullable<int> _DepartureID;
        public Nullable<int> DepartureID { get => _DepartureID; set { _DepartureID = value; OnPropertyChanged(); } }
        private Nullable<int> _DestinationID;
        public Nullable<int> DestinationID { get => _DestinationID; set { _DestinationID = value; OnPropertyChanged(); } }
        private Nullable<decimal> _Price;
        public Nullable<decimal> Price { get => _Price; set { _Price = value; OnPropertyChanged(); } }
        public int OwnedCompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyTicket> MonthlyTickets { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandarTicket> StandarTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSold> TicketSolds { get; set; }
    }
}
